name: Ejecutar bot cada 10 minutos

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-22.04

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Listar archivos y carpetas
      run: ls -la

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
        pip list
        which python

    - name: Mostrar versión de Python
      run: python --version

    - name: Ejecutar bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python bot_unicen.py
